function em = compareDistance(b, b_est)
    % Lower distances from both left and right steps
    em.low = calcErrorMetrics([b.vals_l(1, :), b.vals_r(1, :)],...
        [b_est.vals_l(1, :), b_est.vals_r(1, :)]);

    % Upper distances from both left and right steps
    em.up = calcErrorMetrics([b.vals_l(2, :), b.vals_r(2, :)],...
        [b_est.vals_l(2, :), b_est.vals_r(2, :)]);

    % Lower and upper distances from all steps
    em.all = calcErrorMetrics(...
        [b.vals_l(1, :), b.vals_l(2, :),...
        b.vals_r(1, :), b.vals_r(2, :)],...
        [b_est.vals_l(1, :), b_est.vals_l(2, :),...
        b_est.vals_r(1, :), b_est.vals_r(2, :)]);
end